language: node_js
node_js:
  - 5.0

sudo: false

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
